import 'package:flutter/material.dart';

ThemeData appTheme = ThemeData(
    brightness: Brightness.light,
    primaryColor:  Colors.yellow[900],
    primaryColorLight: Colors.yellow[100],
    primaryColorDark: Colors.orange[900],
    cardColor: Colors.grey[50],
    textSelectionHandleColor: Colors.white,
    backgroundColor: Colors.grey[200],
    splashColor: Colors.grey[300],
    canvasColor: Colors.white,
    errorColor: Colors.red,
    cursorColor: Colors.white,
    hoverColor: Colors.grey[500],
    secondaryHeaderColor: Colors.deepPurple,
    textSelectionColor: Colors.orange,
    accentColor: Colors.pink,
    dividerColor: Colors.grey,
    disabledColor: Colors.grey,
    bottomAppBarColor: Colors.white,
    dialogBackgroundColor: Colors.white,
    buttonColor: Colors.pinkAccent,
    focusColor: Colors.white,
    highlightColor: Colors.purple[50],
    hintColor: Colors.grey,
    unselectedWidgetColor: Colors.grey[200],
    indicatorColor: Colors.redAccent,
    selectedRowColor: Colors.tealAccent,
    toggleableActiveColor: Colors.deepOrangeAccent,
    scaffoldBackgroundColor: Colors.white,
    fontFamily: 'ZillaSlab',
    dialogTheme: DialogTheme(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(25))),
    buttonTheme: ButtonThemeData(buttonColor: Colors.yellow[900], shape: StadiumBorder()));