name: apptemplate
description: Template App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^3.1.3
    #google_sign_in: ^4.1.1
    #firebase_auth: ^0.15.4
    #firebase_core: ^0.4.3+3
    #firebase_analytics: ^5.0.11
    #google_maps_flutter: ^0.5.22+2
    #permission_handler: ^4.2.0+hotfix.3
    #cached_network_image: ^2.0.0
  rxdart: ^0.23.1
    #flutter_launcher_icons: ^0.7.4
    #location: 2.3.5
    #screenshot: ^0.1.1
    #timeago: ^2.0.26
    #http: ^0.12.0+4
    #flutter_cache_manager: ^1.1.3
    #path_provider: ^1.6.1
    #firebase_remote_config: ^0.3.0+1
    #equatable: ^1.0.3
    #cloud_firestore: ^0.13.1
    #data_connection_checker: ^0.3.4
    #keyboard_visibility: ^0.5.6
  package_info: ^0.4.0+13
    #webview_flutter: ^0.3.19+6
    #uuid: ^2.0.4
  material_design_icons_flutter: ^3.4.4795
    #firebase_messaging: ^6.0.9
  store_redirect: ^1.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/locale/i18n_en.json
    - assets/locale/i18n_it.json
